from app import app
from flask import Flask, jsonify
from marshmallow.exceptions import ValidationError

# ! This is our error handler. It handles form validation errors and generic errors. Both will pass
# ! whatever error is generated by SQLAlchemy or marshmallow, as well as a string to help us
# ! identify which kind of error has been created.

@app.errorhandler(ValidationError)
def validation_error(e):
    return { "errors": e.messages, "Message": "Something went wrong in validation" }, 400

@app.errorhandler(Exception)
def generic_error(e):
    if (str(e) == 'You must have a valid email address'):
        return {"email": "You must have a valid email address"}, 405
    else:
        return {"username": "This username already exists, please use another one"}, 401
